version: "3.8"

services:
  db:
    image: mariadb:latest
    volumes:
      - C:\src\ems\mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: emsdb
      MYSQL_USER: emsUser
      MYSQL_PASSWORD: 123456
  app:
    image: ems:latest
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/emsdb?createDatabaseIfNotExist=1